docs/OVERVIEW.md

This adds a little more information around what is necessary to get Turbo Streams running out of the box. I picked an arbitrary example which may need to be adjusted but I think mentioning that you need the domid in the partial may help clarify how it works.

Adds clarification on Turbo Streams Partial

---

src/TurboStreamResponseMacro.php
tests/Http/ResponseMacrosTest.php
tests/Stubs/views/_test_model_soft_delete.blade.php

Hi @tonysm,
I don't think soft-deletes are handle as regular deletes right now for default Turbo Stream.
According to this line: https://github.com/tonysm/turbo-laravel/blob/0.3.2/src/TurboStreamResponseMacro.php#L19
You check if the model exists, but a soft deleted model response to `true` on this `exists` attribute.
In this pull request I add the fix below and a corresponding test:
```php
if (! $model->exists ||
(method_exists($model, 'trashed') && $model->trashed())
) {
return $this->renderModelDeletedStream($model);
}
```
If you remove my fix, the new test will failed with this error:
```
There was 1 failure:
1) Tonysm\TurboLaravel\Tests\Http\ResponseMacrosTest::streams_model_on_soft_delete
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'<turbo-stream …
```

Handle soft-deletes as regular deletes for Turbo Stream

---

README.md
composer.json
src/Broadcasters/LaravelBroadcaster.php
src/Broadcasting/PendingBroadcast.php
src/Models/Broadcasts.php
src/NamesResolver.php
src/TurboServiceProvider.php
src/Views/RecordIdentifier.php
src/helpers.php
tests/Models/BroadcastsModelTest.php
tests/Views/RecordIdentifierTest.php

- **BC**: removes the `turbo_channel` and `turbo_channel_auth` helper functions because, because now Laravel has the conventions built-in. Because of this, we are requiring Laravel `^8.46` now.
- Use `dispatch_sync` instead of `dispatch_now` because the latter was deprecated

Upgrade to Laravel ^8.46

---

README.md
composer.json
src/Commands/TurboInstallCommand.php
src/Http/PendingTurboStreamResponse.php
src/Models/Broadcasts.php
src/TurboServiceProvider.php
stubs/resources/js/alpine.js
tests/Http/ResponseMacrosTest.php
tests/Models/BroadcastsModelTest.php

- Adds the `broadcastAfter` and `broadcastBefore` methods as well as the `broadcastAfterTo` and `broadcastBeforeTo` to the `Broadcasts` trait
- Adds the `before()` and `after()`  methods to the Turbo Stream response builder, so you can do things like `response()->turboStream()->before($model, 'dom_id')`
- Change the installation to make sure Alpine 3 is installed, and add the snippet that Caleb shared
- Change the installation to make sure Turbo ^7.0.0-beta.7 is installed
- Require Laravel `^8.47` so I can use the scoped instances for the turbo helper, instead of Singleton
- Updated the documentation to mention the new broadcast methods and remove reference to the alpine bridge
---
closes #24 #23

Alpine 3, Laravel ^8.47, and Turbo v7.0.0-beta.7

---

src/Models/Naming/Name.php
src/Views/RecordIdentifier.php
src/Views/TurboStreamable.php
src/helpers.php
tests/Stubs/Models/TestTurboStreamable.php
tests/TestTurboStreamable.php
tests/Views/RecordIdentifierStreamableTest.php
tests/Views/RecordIdentifierTest.php
tests/Views/ViewHelpersTest.php

This PR adds the ability for any PHP object to be turbo-streamable by implementing the `TurboStreamable` interface.
I'm the developer of a PHP package called [LdapRecord](https://github.com/DirectoryTree/LdapRecord) that heavily integrates into Laravel and want to be able to use turbo-laravel with LdapRecord models. This isn't possible currently, since Eloquent models are type-hinted into this package.
This PR opens the door for any PHP object to be "turbo-streamable" by implementing a `getDomId()` method.
In my case, this is how I would utilize this with LdapRecord models:
```php
use LdapRecord\Models\Model;
use Tonysm\TurboLaravel\Views\TurboStreamable;
class User extends Model implements TurboStreamble
{
public function getDomId()
{
return $this->getObjectGuid();
}
}
```
The namespace …

Add ability for other resources to be turbo-streamable

---

README.md
src/Commands/TurboInstallCommand.php
src/Testing/AssertableTurboStream.php
src/Testing/ConvertTestResponseToTurboStreamCollection.php
src/Testing/InteractsWithTurbo.php
src/Testing/TurboStreamMatcher.php
src/TurboServiceProvider.php
tests/Http/TurboStreamResponseTest.php
tests/Stubs/views/turbo_streams.blade.php
tests/Testing/TurboStreamMatcherTest.php

- Adds the `$response->assertTurboStream` macro which accepts an optional callback that receives an object of the `AssertableTurboStream` class, which should give developers some methods like `->has(3)` which asserts that there are 3 turbo stream tags, and a `->hasTurboStream(fn)` which receives a callback so you can filter and match the Turbo Stream you want check that is present, this one receives a callback and you can chain `->where()` calls to each turbo stream and also chain a `->see()` and other regular Laravel assertions on the contents of the template inside these turbo streams (make sure you call `->see()` after your `->where()` filters).
- Pulls the Turbo.js version `^7.0.0-beta.8` for fresh installs.
---
Todo:

Better Testing

---

README.md
src/TurboServiceProvider.php
tests/Http/RequestMacrosTest.php

- Adds the `request()->wasFromTurboNative()` macro, which can be used in content negotiation

Adds the wasFromTurboNative request macro

---

README.md
src/Facades/Turbo.php
src/Http/Middleware/RouteRedirectGuesser.php
src/Http/Middleware/TurboMiddleware.php
src/Turbo.php
src/TurboServiceProvider.php
tests/Http/Middleware/TurboMiddlewareTest.php

- Instead of redirecting to the form route when a `ValidationException` is thrown, we're following the redirects internally returning the form response body with a 422 status code, which is better handled by Turbo Native.
---
Issue #29 
This borrows from the [Inertia dialog implementation](https://github.com/inertiajs/inertia-laravel/commit/35367f0b2ff68822e27185f49ddfa5dd7846386e).

Change the default invalid form handling to follow redirects internally

---

README.md
resources/views/components/turbo-frame.blade.php
resources/views/components/turbo-stream-from.blade.php
resources/views/components/turbo-stream.blade.php
resources/views/turbo-stream.blade.php
src/TurboServiceProvider.php
src/Views/Components/Frame.php
src/Views/Components/Stream.php
src/Views/Components/StreamFrom.php

- Adds new Blade components for `x-turbo-frame`, `x-turbo-stream`, and `x-turbo-stream-from` so we can simplify usage
---
This pushes some decisions to the package itself. Below you can find the before/after of using each component.
```blade
<turbo-frame id="@domid($post)">
@include('posts._post', ['post' => $post])
</turbo-frame>
```
We can now write it like:
```blade
<x-turbo-frame :id="$post">
@include('posts._post', ['post' => $post])
</x-turbo-frame>
```
Notice that you may pass an instance of an Eloquent Model to the `id` property, which will be used to generate a DOM ID using the `dom_id` function that ships with the package. There's no need to use the `@domid` Blade directive here.
The available properties are: `src`, `loading`, and `target`. Additionally, any other attributes …

Adds Turbo Frame, Turbo Stream, and Turbo Stream From Blade components

---

stubs/resources/js/libs/turbo.js

The initialization of turbo is already done and assigned to window by turbo, so this should be enough.

Fix turbo initialization

---

.github/workflows/run-tests.yml
README.md
composer.json
resources/views/components/stream.blade.php
resources/views/turbo-stream.blade.php
src/Http/PendingTurboStreamResponse.php
src/Http/TurboStreamResponseFailedException.php
src/Models/Broadcasts.php
tests/Http/ResponseMacrosTest.php
tests/Models/BroadcastsModelTest.php

- Allow passing a string to all the shorthand stream builder methods instead of only accepting model instances
- The `before` and `after` shorthand were accepting two properties: a model instance, which was used to derive the view and view data to be rendered, and a string target, which would be used as the Turbo Stream target. Now, it only accepts the model, which can either be an Eloquent instance or a string. **This was technically a BREAKING CHANGE. However, I'm considering the old behavior a bug since it wasn't meant to be like that.** If you're using the before/after shorthand, take a closer look a those changes
- When using the auto-broadcasting feature, recently created models would be broadcasted to the model's channel as described in Laravel's channel conventions. However, since …

Some Tweaks

---

.github/workflows/run-tests-l8.yml
.github/workflows/run-tests.yml
composer.json
tests/Http/ResponseMacrosTest.php

- While I was working on some upgrades, I dropped Laravel and PHP versions requirements, but I haven't tagged a major version, so I'm bringing it back

Bring back Laravel 8 builds

---

README.md

The documentation currently incorrectly specifies that form submissions will get a `Content-Type` of `text/vnd.turbo-stream.html`. In reality, the submission gets an `Accept` of that value.

Fix header used for Turbo Streams request in docs

---

src/TurboServiceProvider.php

By adding these return types, we can call `\Response::turboStream(...)` and get the appropriate type hinting functionalities (after running `php artisan ide-helper:generate` from https://github.com/barryvdh/laravel-ide-helper).

Add return types to request and response macro's

---

resources/views/components/stream.blade.php
resources/views/turbo-stream.blade.php
src/Broadcasters/Broadcaster.php
src/Broadcasters/LaravelBroadcaster.php
src/Broadcasting/PendingBroadcast.php
src/Events/TurboStreamBroadcast.php
src/Http/PendingTurboStreamResponse.php
src/Jobs/BroadcastAction.php
src/Views/Components/Stream.php
tests/Events/TurboStreamBroadcastTest.php
tests/Http/ResponseMacrosTest.php
tests/Http/TurboStreamResponseTest.php
tests/Models/BroadcastsModelTest.php
tests/Stubs/views/turbo_streams.blade.php
tests/Testing/TurboStreamMatcherTest.php
tests/Views/ComponentsTest.php

This PR adds support to Turbo Streams Targeting Multiple Elements, by adding the option to the response macros and all underlying Blade components.
https://turbo.hotwired.dev/reference/streams#targeting-multiple-elements
We realize that this is an impactful PR, and we don't expect it to be merged without change or further discussion.
Please view this PR as the start of a conversation around the topic.
We have tried to balance staying compatible with the syntax from the Turbo handbook (so no separate `<turbo-stream>` component with `targets=` support) with not making any breaking changes to the API of this package, but we have had to make a few hard choices along the way. In particular, it was not possible to not make any breaking changes to the `Stream` component constructor without …

Implement streams Targeting Multiple Elements

---

resources/views/components/stream.blade.php
src/Broadcasters/Broadcaster.php
src/Broadcasters/LaravelBroadcaster.php
src/Broadcasting/PendingBroadcast.php
src/Events/TurboStreamBroadcast.php
src/Exceptions/TurboStreamTargetException.php
src/Http/PendingTurboStreamResponse.php
src/Jobs/BroadcastAction.php
src/Models/Broadcasts.php
src/Testing/AssertableTurboStream.php
src/Testing/TurboStreamMatcher.php
src/Views/Components/Stream.php
tests/Events/TurboStreamBroadcastTest.php
tests/Http/ResponseMacrosTest.php
tests/Http/TurboStreamResponseTest.php
tests/Models/BroadcastsModelTest.php
tests/Testing/TurboStreamMatcherTest.php
tests/Views/ComponentsTest.php

- Adds new `appendAll`, `prependAll`, `beforeAll`, `afterAll`, `updateAll`, `replaceAll`, and `removeAll` methods
- **BC** The `Broadcaster` interface and concrete implementation API changed
- **BC** The `PendingBroadcast` parameter order changed 
- **BC**: The `TurboStreamBroadcast` parameter order changed
- The `TurboStreamMatcher` is now cloned whenever the `where()` or `see()` methods are called to avoid some left-overs
---
This is a follow-up PR on the work done in https://github.com/tonysm/turbo-laravel/pull/86

Tweaks targets

---

src/Commands/TurboInstallCommand.php
stubs/resources/js/controllers/hello_controller.js
stubs/resources/js/controllers/index-importmap.js
stubs/resources/js/controllers/index-node.js
stubs/resources/js/libs/stimulus-importmap.js
stubs/resources/js/libs/stimulus-node.js

- Remove Stimulus stubs and options from the install command. This will be moved to its own [stimulus-laravel](https://github.com/tonysm/stimulus-laravel) package

Remove Stimulus stubs and install options

---

stubs/resources/js/elements/turbo-echo-stream-tag.js

- Fixes the `turbo-echo-stream-source` custom HTML tag not being able to connect to public channels

Fix the turbo-echo-stream-source custom tag was not connecting to public channel

---

src/TurboServiceProvider.php

- Use the HTTP Kernel instead of `Route` facade to prepend the Turbo Laravel middleware. The Turbo Middleware was previously being automatically prepended to the web route group, but something must have changed in Laravel in version 10 as it's no longer the case. Using the HTTP Kernel instead works.

Fix middleware not automatically registered

---

src/Models/Naming/Name.php

I have a project with a lot of components and `dom_id` or `dom_class` being called hundreds of times on each page load.
This PR optimizes the performance of these functions by reusing `Name` instances such that the name for a particular class only ever has to be calculated once.
The calculation (in the `Tonysm\TurboLaravel\Models\Naming\Name::build` method) is actually somewhat expensive when done in large quantities – mostly as a result of the use of the `config` helper in `removeRootNamespaces` (resolving from the container each time adds up), and the call to `Str::plural`.
Ideally the public properties of the `Name` class would be made `readonly` so these instances are immutable, however would require dropping PHP 8.0 support.

Reuse `Name` instances to improve performance

---

src/Models/ModelObserver.php
tests/Models/BroadcastsModelTest.php
tests/Stubs/views/posts/_post.blade.php
tests/TestCase.php

- Model touching wasn't triggering the parent's broadcasts. Looks like only the `saved` event is fired when the parent's timestamps are updated, not the `updated` event.

Fix model broadcast was not being triggered when using model touching
